CREATE TABLE `external_lab_request` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `labNo` varchar(100) DEFAULT NULL,
  `parentLabNo` varchar(100) DEFAULT NULL,
  `requestingClinician` varchar(100) DEFAULT NULL,
  `investigation` varchar(100) DEFAULT NULL,
  `requestDate` datetime DEFAULT NULL,
  `patient_id` varchar(100) DEFAULT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `dateOfBirth` datetime DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `gender` varchar(45) DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  `postalCode` varchar(45) DEFAULT NULL,
  `phoneNumber` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `test_completed` bit(1) DEFAULT b'0',
  `result` varchar(45) DEFAULT NULL,
  `result_returned` bit(1) DEFAULT b'0',
  `revisitNumber` int(11) DEFAULT NULL,
  `cost` int(11) DEFAULT NULL,
  `patientContact` varchar(45) DEFAULT NULL,
  `receiptNumber` varchar(45) DEFAULT NULL,
  `waiverNo` varchar(45) DEFAULT NULL,
  `comments` varchar(200) DEFAULT NULL,
  `provisionalDiagnosis` varchar(45) DEFAULT NULL,
  `system_id` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1
